### ISSUE TITLE
Release 0.2.0 failed

### ISSUE THREAD

**Issue by randm-ch** [kitlangton/formula#13]
Hi @kitlangton 

Just noticed that release 0.2.0 failed to publish with some `gpg`/sign error:
https://github.com/kitlangton/formula/actions/runs/10372006834/job/28713666269

Would be great if you could have a look.

Cheers!

**Comment by kitlangton** [comment]
Ah, thanks for pointing that out! I had some old credentials in my GitHub secrets that I've since updated. 🙂 It should be released now! Bon Appétit.
