### ISSUE TITLE
Sourcemaps?

### ISSUE THREAD

**Issue by jetaggart** [kitlangton/formula#2]
Hey, using your example as as starting off point, thank you for putting this out there!

I'm curious if you have managed to get sourcemaps working? When I turn them on vite throws a cryptic error:

`ENOENT: no such file or directory, open '/Users/jefftaggart/code/ghostnote/web/target/scala-3.0.0-RC3/web-fastopt/https:/raw.githubusercontent.com/scala-js/scala-js/v1.5.1/javalanglib/src/main/scala/java/lang/System.scala'
`

**Comment by kitlangton** [comment]
😮! I don't think I ever noticed this issue. Apologies for that!

However, I never have gotten source maps to work. Though, I haven't invested too much time into it either. Were you able to? 😄

**Comment by jetaggart** [comment]
Ha, no worries. I can't even remember at this point, but I doubt it.
