### ISSUE TITLE
Do you plan to add a license?

### ISSUE THREAD

**Issue by scalavision** [kitlangton/formula#3]
Hi,

I am not able to find any license, could that be added?

I think this is a very nice example of the excellence of Scala.js, how it enables to build quite advanced form setup, without too much complexity. Also, thanks for putting the video describing how it was built. It is very helpful.

**Comment by kitlangton** [comment]
Oh yeah. I'll add one right now :D

**Comment by kitlangton** [comment]
License created 👯
